apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: compositevms.example.org
  labels:
    provider: terraform
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: example.org/v1alpha1
    kind: CompositeVM
  resources:
    - name: terraform-gcp-vm
      base:
        apiVersion: tf.crossplane.io/v1alpha1
        kind: Workspace
        spec:
          forProvider:
            source: Inline
            module: |
              // The values of these variables are set by the 'vars' YAML block
              // below, which can in turn be set by composition patches.
              variable "machine_type" {
                type = string
              }

              variable "zone" {
                type = string
              }

              // Expose the VM's internal IP address as a Crossplane connection
              // secret key named 'address'.
              output "address" {
                value = google_compute_instance.vm.network_interface.0.network_ip
              }

              resource "google_compute_instance" "vm" {
                // We use the workspace name to derive the compute instance's
                // name from the workspace's external name annotation.
                name         = terraform.workspace

                // The machine type and zone are exposed as Terraform variables.
                // This lets us use FromCompositeFieldPath patches to derive
                // their values from the composite resource.
                machine_type = var.machine_type
                zone         = var.zone
              
                boot_disk {
                  initialize_params {
                    image = "debian-cloud/debian-9"
                  }
                }
              
                network_interface {
                  network = "default"
              
                  access_config {
                    // Ephemeral IP
                  }
                }
              }
            vars:
              # We patch in the values for these variables below.
              - key: machine_type
              - key: zone
          writeConnectionSecretToRef:
            namespace: crossplane-system
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: "metadata.annotations[crossplane.io/external-name]"
          toFieldPath: "metadata.annotations[crossplane.io/external-name]"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.size"
          toFieldPath: "spec.forProvider.vars[0].value"
          transforms:
            - type: map
              map:
                small: e2-standard-2
                medium: e2-standard-8
                large: e2-standard-32
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.location"
          toFieldPath: "spec.forProvider.vars[1].value"
          transforms:
            - type: map
              map:
                east-coast: us-east1-b
                west-coast: us-west1-b
        - type: FromCompositeFieldPath
          fromFieldPath: "metadata.uid"
          toFieldPath: "spec.writeConnectionSecretToRef.name"
          transforms:
            - type: string
              string:
                fmt: "%s-vm"
      connectionDetails:
        - fromConnectionSecretKey: address