---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: compositevms.example.org
spec:
  group: example.org
  names:
    kind: CompositeVM
    plural: compositevms
  claimNames:
    kind: VM
    plural: vms
  connectionSecretKeys:
    - address
  defaultCompositionRef:
    name: compositevms.example.org
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  size:
                    type: string
                    default: small
                    enum:
                     - small
                     - medium
                     - large
                  location:
                    type: string
                    enum:
                     - west-coast
                     - east-coast
                required:
                  - size
                  - location
            required:
              - parameters