apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: tf.compositebuckets.example.org
  labels:
    provider: terraform
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: example.org/v1alpha1
    kind: CompositeBucket
  resources:
    - name: terraform-gcp-bucket
      base:
        apiVersion: tf.crossplane.io/v1alpha1
        kind: Workspace
        spec:
          forProvider:
            source: Remote
            module: git::http://github.com/negz/provider-terraform-examples//migrating-from-terraform/tf
            vars:
              # We patch in the values for this variable below.
              - key: location
          writeConnectionSecretToRef:
            namespace: crossplane-system
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: "metadata.annotations[crossplane.io/external-name]"
          toFieldPath: "metadata.annotations[crossplane.io/external-name]"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.location"
          toFieldPath: "spec.forProvider.vars[0].value"
          transforms:
            - type: map
              map:
                USA: US
                Europe: EU
        - type: FromCompositeFieldPath
          fromFieldPath: "metadata.uid"
          toFieldPath: "spec.writeConnectionSecretToRef.name"
          transforms:
            - type: string
              string:
                fmt: "%s-bucket"
      connectionDetails:
        - fromConnectionSecretKey: address
