---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: compositebuckets.example.org
spec:
  group: example.org
  names:
    kind: CompositeBucket
    plural: compositebuckets
  claimNames:
    kind: Bucket
    plural: buckets
  connectionSecretKeys:
    - address
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  location:
                    type: string
                    enum:
                     - USA
                     - Europe
                required:
                  - location
            required:
              - parameters